specfile_path: fmf.spec
synced_files:
    - fmf.spec
jobs:
- job: copr_build
  trigger: pull_request
  metadata:
    targets:
      - fedora-rawhide-x86_64
      - fedora-30-x86_64
      - fedora-29-x86_64
